repos:
  - hooks:
      - id: black
        args:
          - --line-length=99
        language_version: python3
    repo: https://github.com/ambv/black
    rev: 23.7.0
  - hooks:
      - id: flake8
        args:
          - "--max-line-length=99"
    repo: https://github.com/pycqa/flake8
    rev: 6.1.0
  - hooks:
      - args:
          - --django
        id: name-tests-test
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0