name: Python Application Testing

on: [push]

env:
  PYTHON_VERSION: "3.10.12"
  PROJECT_FOLDER: src
  TEST_FOLDER: tests
  COVERAGE_LIMIT: 0
    
jobs:
   Linting-testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{env.PYTHON_VERSION}}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry && poetry install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Security Analysis with bandit
      run: |
        mkdir ci-logs
        poetry run bandit -r -lll  -f txt -o ci-logs/bandit.log ${{env.PROJECT_FOLDER}} ${{env.TEST_FOLDER}}
        
    - name: Archive bandit report
      uses: actions/upload-artifact@v2
      with:
        name: bandit-report
        path: ci-logs/bandit.log

    - name: Test with pytest
      run: |
        poetry run python -m pytest -v ${{env.TEST_FOLDER}}